'use strict';const test=require('node:test');const assert=require('node:assert/strict');const {authorizeTransition,buildRenderManifest,evaluateOutput,validateAsset,validateProject,validateStemRequest}=require('../domain/musicPolicy');const {providerReadiness,requireProvider}=require('../services/providerBoundary');
function project(){return {tenantId:'t1',name:'song',projectVersion:'v2',brandPolicyVersion:'brand-v1',moderationPolicyVersion:'safe-v3',moderationPassed:true,impersonatesLivingArtist:false,assets:[{id:'a1',kind:'audio',contentDigest:'a'.repeat(64),containsPerson:true,performerConsent:true,rights:{licenseId:'L1',territories:['US']}}],timeline:{tracks:[{id:'t1',clips:[{assetId:'a1',startSeconds:0,durationSeconds:5}]}]},export:{sampleRate:48000,bitDepth:24,format:'wav'}};}
test('validates rights consent versions moderation assets and editable timeline',()=>{const result=validateProject(project());assert.equal(result.ok,true);assert.match(result.inputDigest,/^[a-f0-9]{64}$/);});
test('rejects missing license expired rights and missing performer consent',()=>{const asset=project().assets[0];asset.performerConsent=false;asset.rights={territories:[],expiresAt:'2020-01-01'};const result=validateAsset(asset);assert.equal(result.ok,false);assert.equal(result.errors.length,4);});
test('rejects living artist impersonation unknown assets and invalid timing',()=>{const invalid=project();invalid.impersonatesLivingArtist=true;invalid.timeline.tracks[0].clips=[{assetId:'missing',startSeconds:-1,durationSeconds:0}];const result=validateProject(invalid);assert.equal(result.ok,false);assert.equal(result.errors.length,3);});
test('render manifest is deterministic versioned and export-compatible',()=>{const first=buildRenderManifest(project()),second=buildRenderManifest(project());assert.deepEqual(first,second);assert.equal(first.sampleRate,48000);assert.equal(first.bitDepth,24);assert.equal(first.format,'wav');assert.match(first.manifestDigest,/^[a-f0-9]{64}$/);});
test('render queue requires rights moderation approvals and providers',()=>{const approvals=[{approvalType:'rights',decision:'approve'},{approvalType:'moderation',decision:'approve'}];assert.equal(authorizeTransition({current:'render_review',next:'queued',actor:{role:'editor'},approvals,providersReady:false}).ok,false);assert.equal(authorizeTransition({current:'render_review',next:'queued',actor:{role:'editor'},approvals,providersReady:true}).ok,true);});
test('publication requires publisher watermark and disclosure evidence',()=>{assert.equal(authorizeTransition({current:'approved',next:'published',actor:{role:'creator'},evidence:{}}).ok,false);assert.equal(authorizeTransition({current:'approved',next:'published',actor:{role:'publisher'},evidence:{watermarkDigest:'x',disclosure:'AI-assisted'}}).ok,true);});
test('stem separator requires durable source model and explicit supported stems',()=>{const valid=validateStemRequest({sourceAssetId:'a1',sourceDigest:'b'.repeat(64),modelVersion:'separator-v1',stems:['vocals','drums']});assert.equal(valid.ok,true);const invalid=validateStemRequest({stems:['magic']});assert.equal(invalid.ok,false);assert.equal(invalid.errors.length,4);});
test('evaluation measures quality timing accessibility brand multilingual and compatibility',()=>{const result=evaluateOutput([{quality:.9,timingFidelity:.8,accessibility:1,brandCompliance:.7,multilingualScore:.6,latencyMs:10,exportDigest:'same'},{quality:.7,timingFidelity:1,accessibility:.8,brandCompliance:.9,multilingualScore:1,latencyMs:20,exportDigest:'same'}]);assert.equal(result.sampleCount,2);assert.equal(result.quality,.8);assert.equal(result.timingFidelity,.9);assert.equal(result.latencyP95Ms,20);assert.equal(result.deterministicCompatibility,true);});
test('evaluation detects incompatible export digests',()=>{const samples=['a','b'].map((exportDigest)=>({quality:1,timingFidelity:1,accessibility:1,brandCompliance:1,multilingualScore:1,latencyMs:1,exportDigest}));assert.equal(evaluateOutput(samples).deterministicCompatibility,false);});
test('providers fail closed until fully configured',()=>{assert.equal(providerReadiness({}).ready,false);assert.throws(()=>requireProvider('stem_separator',{}),/not ready/);const env={};for(const name of ['MEDIA_MODEL','RIGHTS_LIBRARY','ASSET_STORAGE','CDN','TRANSCRIPTION','TRANSLATION','PUBLISHING','STEM_SEPARATOR']){env[`${name}_PROVIDER_ENABLED`]='true';env[`${name}_PROVIDER_URL`]=`https://${name.toLowerCase()}.example.invalid`;env[`${name}_PROVIDER_TOKEN`]='runtime';}assert.equal(providerReadiness(env).ready,true);});
